//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Api
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bug_reporting
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Current_behaviour { get; set; }
        public string Expected_behaviour { get; set; }
        public Nullable<int> Bug_reporting_collection_id { get; set; }
        public string Browser { get; set; }
        public string Operating_system { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
