//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.GFI.TestLanding
{
    using System;
    using System.Collections.Generic;
    
    public partial class Build
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Build()
        {
            this.Tools_Test = new HashSet<Tools_Test>();
        }
    
        public int id { get; set; }
        public int id_project { get; set; }
        public string tool_name { get; set; }
        public Nullable<System.DateTime> date_start { get; set; }
        public Nullable<System.DateTime> date_end { get; set; }
        public string status { get; set; }
        public string general_message { get; set; }
        public Nullable<int> id_batteryTest { get; set; }
        public Nullable<int> id_machine { get; set; }
        public Nullable<int> pass_tests { get; set; }
        public string duration { get; set; }
        public Nullable<int> total_tests { get; set; }
        public Nullable<int> failed_tests { get; set; }
        public Nullable<int> skipped_tests { get; set; }
        public string username { get; set; }
    
        public virtual BatteryTest BatteryTest { get; set; }
        public virtual Machine Machine { get; set; }
        public virtual Project Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tools_Test> Tools_Test { get; set; }
    }
}
